# Generated by Django 5.0.2 on 2024-04-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="summary",
            field=models.TextField(max_length=200),
        ),
    ]
