# Generated by Django 5.0.2 on 2024-04-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdf", "0002_alter_profile_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="author",
            field=models.CharField(default="xyz", max_length=200),
            preserve_default=False,
        ),
    ]
