# Generated by Django 5.0.2 on 2024-04-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdf", "0003_profile_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="soft_skills",
            field=models.TextField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="total_experience",
            field=models.IntegerField(default=1),
        ),
    ]
